pages:
  image: 
    immc/onwards-doc:v0.2
  only:
    - release
  script:
    - make -C onwards/lagSolver/libc/
    - export ONWARDS_PATH=$(pwd)
    - sphinx-build -b html docs/source public
  artifacts:
    paths:
    - public


deploy-github:
  image:
    alpine:latest
  only:
    - release
  stage:
    deploy
  variables:
    PUBLIC_REPO_URL: "git@github.com:vortexlab-uclouvain/onwards.git"
  before_script:
    - apk add git
    - apk add openssh
    - eval $(ssh-agent -s)
    - chmod 400 "$GITHUB_SSH_KEY"
    - ssh-add "$GITHUB_SSH_KEY"
    - mkdir -p ~/.ssh
    - cp "$SSH_KNOWN_HOSTS" ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - git push -u $PUBLIC_REPO_URL --force HEAD:main